
max_width = 120

edition = "2018"

blank_lines_upper_bound = 4

enum_discrim_align_threshold = 1024

struct_field_align_threshold = 1024

merge_imports = true

fn_single_line = true

reorder_imports = false

normalize_comments = true

reorder_impl_items = true

combine_control_expr = false

use_field_init_shorthand = true

condense_wildcard_suffixes = true

format_code_in_doc_comments = true

indent_style = "Visual"

trailing_comma = "always"

ignore = [
    "examples/kg_test.rs"
]

type_punctuation_density = "Compressed"
